"""
api/events.py
=============
POST /api/events — Event Distribution and Neo4j Graph Storage Endpoint.

Receives the completed structured FraudEvent JSON generated by /api/analyze
and persists it into the Neo4j graph for future campaign correlation.
"""

from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel, Field
from datetime import datetime

from neo4j import get_event_repository, EventRepository

router = APIRouter(prefix="/api", tags=["events"])


class EventStoreResponse(BaseModel):
    status: str
    storage: str
    event_id: str
    user_id: str
    stored_at: str
    graph_summary: Dict[str, Any] = Field(default_factory=dict)


@router.post(
    "/events",
    response_model=EventStoreResponse,
    summary="Store a completed structured fraud event into Neo4j graph database",
)
def store_fraud_event(
    event_payload: Dict[str, Any],
    repo: EventRepository = Depends(get_event_repository),
):
    """
    Ingest a completed analysis event and persist graph entities:
      - (User) -[:RECEIVED]-> (Event)
      - (Event) -[:FROM]-> (Phone)
      - (Event) -[:CONTAINS]-> (URL / Domain)
      - (Event) -[:TARGETS]-> (FraudType)
    """
    if not event_payload:
        raise HTTPException(status_code=400, detail="Empty event payload")

    try:
        result = repo.store_event(event_payload)
        return EventStoreResponse(**result)
    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to process event storage: {type(exc).__name__}",
        )
