export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🌐' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appTitle: 'SeniorShield',
    appSubtitle: 'Autonomous Scam Defense',
    helpline: 'Emergency Cyber Helpline (1930)',
    riskExposure: 'CUMULATIVE RISK EXPOSURE',
    goldenRules: 'Golden Safety Rules for Seniors',
    ruleEb: 'Electricity Boards never cut off power at night without paper notices.',
    rulePolice: 'Police & CBI never arrest citizens over phone or Skype/WhatsApp video calls.',
    ruleBank: 'Banks never send apps (.apk links) or ask for OTPs to update KYC.',
    blockSender: 'Hang Up & Block Sender',
    alertGuardian: 'Alert Family Guardian (SMS)',
    whatThisMeans: 'WHAT THIS MEANS FOR YOU',
    whatYouMustDo: 'WHAT YOU MUST DO NOW:',
    impersonatedEntity: 'IMPERSONATED ENTITY',
    targetedAssets: 'Targeted Assets at Stake:',
    dismiss: 'Dismiss',
    blockReject: 'Block & Reject',
  },
  ta: {
    appTitle: 'சீனியர் ஷீல்ட்',
    appSubtitle: 'முதியோர் மோசடி தடுப்பு கவசம்',
    helpline: 'சைபர் குற்ற அவசர உதவி (1930)',
    riskExposure: 'ஒட்டுமொத்த ஆபத்து அளவு',
    goldenRules: 'முதியோர்களுக்கான தங்க பாதுகாப்பு விதிகள்',
    ruleEb: 'மின்சார வாரியம் ஒருபோதும் இரவில் காகித அறிவிப்பு இன்றி மின்சாரத்தை துண்டிக்காது.',
    rulePolice: 'போலீஸ் அல்லது சிபிஐ ஒருபோதும் தொலைபேசி அல்லது வீடியோ அழைப்பில் கைது செய்யாது.',
    ruleBank: 'வங்கிகள் ஒருபோதும் ஆப் (.apk) இணைப்புகளை அனுப்பாது அல்லது OTP கேட்காது.',
    blockSender: 'அழைப்பை துண்டித்து பிளாக் செய்யவும்',
    alertGuardian: 'குடும்ப பாதுகாவலருக்கு SMS அனுப்பவும்',
    whatThisMeans: 'இதன் பொருள் என்ன',
    whatYouMustDo: 'நீங்கள் இப்போது செய்ய வேண்டியது:',
    impersonatedEntity: 'ஆள்மாறாட்டம் செய்யப்பட்ட துறை',
    targetedAssets: 'ஆபத்தில் உள்ள உடைமைகள்:',
    dismiss: 'விலக்கு',
    blockReject: 'தடை செய்',
  },
  hi: {
    appTitle: 'सीनियर शील्ड',
    appSubtitle: 'वरिष्ठ नागरिक धोखाधड़ी सुरक्षा',
    helpline: 'आपातकालीन साइबर हेल्पलाइन (1930)',
    riskExposure: 'कुल जोखिम स्तर',
    goldenRules: 'वरिष्ठ नागरिकों के लिए सुरक्षा नियम',
    ruleEb: 'बिजली विभाग रात में बिना लिखित नोटिस के बिजली नहीं काटता।',
    rulePolice: 'पुलिस या सीबीआई कभी फोन या वीडियो कॉल पर डिजिटल गिरफ्तारी नहीं करती।',
    ruleBank: 'बैंक कभी भी ऐप (.apk) लिंक नहीं भेजते और न ही OTP मांगते हैं।',
    blockSender: 'कॉल काटें और ब्लॉक करें',
    alertGuardian: 'अभिभावक को SMS भेजें',
    whatThisMeans: 'आपके लिए इसका क्या मतलब है',
    whatYouMustDo: 'अब आपको क्या करना चाहिए:',
    impersonatedEntity: 'नकली विभाग/अधिकारी',
    targetedAssets: 'खतरे में संपत्तियां:',
    dismiss: 'खारिज करें',
    blockReject: 'ब्लॉक करें',
  },
  te: {
    appTitle: 'సీనియర్ షీల్డ్',
    appSubtitle: 'వృద్ధుల మోసాల రక్షణ వ్యవస్థ',
    helpline: 'ఎమర్జెన్సీ సైబర్ హెల్ప్‌లైన్ (1930)',
    riskExposure: 'మొత్తం రిస్క్ స్థాయి',
    goldenRules: 'వృద్ధులకు రక్షణ సూత్రాలు',
    ruleEb: 'విద్యుత్ శాఖ రాత్రి పూట నోటీసు లేకుండా విద్యుత్ సరఫరా ఆపదు.',
    rulePolice: 'పోలీసులు లేదా CBI ఫోన్/వీడియో కాల్‌లో అరెస్టు చేయరు.',
    ruleBank: 'బ్యాంకులు ఎప్పుడూ .apk లింకులు పంపవు లేదా OTPలు అడగవు.',
    blockSender: 'కాల్ కట్ చేసి బ్లాక్ చేయండి',
    alertGuardian: 'సంరక్షకుడికి SMS పంపండి',
    whatThisMeans: 'దీని అర్థం ఏమిటి',
    whatYouMustDo: 'మీరు ఇప్పుడు ఏమి చేయాలి:',
    impersonatedEntity: 'నకిలీ అధికారి/సంస్థ',
    targetedAssets: 'ప్రమాదంలో ఉన్న ఆస్తులు:',
    dismiss: 'రద్దు చేయి',
    blockReject: 'బ్లాక్ చేయి',
  },
  kn: {
    appTitle: 'ಸೀನಿಯರ್ ಶೀಲ್ಡ್',
    appSubtitle: 'ಹಿರಿಯ ನಾಗರಿಕರ ರಕ್ಷಣೆ',
    helpline: 'ತುರ್ತು ಸೈಬರ್ ಸಹಾಯವಾಣಿ (1930)',
    riskExposure: 'ಒಟ್ಟು ಅಪಾಯದ ಮಟ್ಟ',
    goldenRules: 'ಹಿರಿಯರಿಗೆ ಪ್ರಮುಖ ಸುರಕ್ಷತಾ ನಿಯಮಗಳು',
    ruleEb: 'ವಿದ್ಯುತ್ ಮಂಡಳಿ ಲಿಖಿತ ಸೂಚನೆ ಇಲ್ಲದೆ ರಾತ್ರಿ ವಿದ್ಯುತ್ ಕಡಿತಗೊಳಿಸುವುದಿಲ್ಲ.',
    rulePolice: 'ಪೊಲೀಸರು ಅಥವಾ CBI ಫೋನ್/ವೀಡಿಯೊ ಕರೆಯಲ್ಲಿ ಬಂಧಿಸುವುದಿಲ್ಲ.',
    ruleBank: 'ಬ್ಯಾಂಕುಗಳು ಎಂದಿಗೂ .apk ಲಿಂಕ್ ಕಳುಹಿಸುವುದಿಲ್ಲ ಅಥವಾ OTP ಕೇಳುವುದಿಲ್ಲ.',
    blockSender: 'ಕರೆ ಕಡಿತಗೊಳಿಸಿ ಬ್ಲಾಕ್ ಮಾಡಿ',
    alertGuardian: 'ಕುಟುಂಬ ಪೋಷಕರಿಗೆ SMS ಕಳುಹಿಸಿ',
    whatThisMeans: 'ಇದರ ಅರ್ಥವೇನು',
    whatYouMustDo: 'ನೀವು ಈಗ ಏನು ಮಾಡಬೇಕು:',
    impersonatedEntity: 'ನಕಲಿ ಸಂಸ್ಥೆ/ಅಧಿಕಾರಿ',
    targetedAssets: 'ಅಪಾಯದಲ್ಲಿರುವ ಸಂಪತ್ತು:',
    dismiss: 'ರದ್ದುಮಾಡು',
    blockReject: 'ನಿರ್ಬಂಧಿಸಿ',
  },
  ml: {
    appTitle: 'സീനിയർ ഷീൽഡ്',
    appSubtitle: 'തട്ടിപ്പ് പ്രതിരോധ കവചം',
    helpline: 'സൈബർ ഹെൽപ്പ്‌ലൈൻ (1930)',
    riskExposure: 'ആകെ അപകടസാധ്യത',
    goldenRules: 'മുതിർന്നവർക്കുള്ള സുരക്ഷാ നിയമങ്ങൾ',
    ruleEb: 'വൈദ്യുതി ബോർഡ് രാത്രിയിൽ അറിയിപ്പില്ലാതെ വൈദ്യുതി വിച്ഛേദിക്കില്ല.',
    rulePolice: 'പോലീസോ സിബിഐയോ ഫോൺ/വീഡിയോ കോളിലൂടെ അറസ്റ്റ് ചെയ്യില്ല.',
    ruleBank: 'ബാങ്കുകൾ ഒരിക്കലും .apk ലിങ്കുകൾ അയക്കുകയോ ഒടിപി ചോദിക്കുകയോ ചെയ്യില്ല.',
    blockSender: 'കോൾ വിച്ഛേദിച്ച് ബ്ലോക്ക് ചെയ്യുക',
    alertGuardian: 'രക്ഷാധികാരിക്ക് SMS അയക്കുക',
    whatThisMeans: 'ഇതിന്റെ അർത്ഥം',
    whatYouMustDo: 'നിങ്ങൾ ഇപ്പോൾ എന്ത് ചെയ്യണം:',
    impersonatedEntity: 'വ്യാജ സംഘടന/ഉദ്യോഗസ്ഥൻ',
    targetedAssets: 'അപകടത്തിലായ ആസ്തികൾ:',
    dismiss: 'തള്ളിക്കളയുക',
    blockReject: 'ബ്ലോക്ക് ചെയ്യുക',
  },
};
